### ISSUE TITLE
Show progress on query param change?

### ISSUE THREAD

**Issue by affanshahid** [Skyleen77/next-nprogress-bar#1]
Great package! Is it possible to show the nav progress when a query param changes?

**Comment by Skyleen77** [comment]
Hello,

Parameter change in URL without page change is also called shallow routing in Next.js.

Many people don't want the progress bar to appear during shallow routing, that's why I included a parameter called shallowRouting to disable the progress bar for shallow routing, like this :

```js
<ProgressBar shallowRouting />
```

If you want to show the progress bar with the shallow routing, just don't add this parameter like this : 

```js
<ProgressBar />
```

If you encounter any other problems, do not hesitate to ask me.
